### ISSUE TITLE
Feature: ClickHouse backend

### ISSUE THREAD

**Issue by AlexAkulov** [adambaumeister/goflow#21]
It seems that ClickHouse (https://github.com/yandex/ClickHouse) is a good choose for this data.

**Comment by adambaumeister** [comment]
Hiya,

Thanks for the interest and recommendation.

I have investigated column-orientated databases already, specifically, Cassandra, as a backend.

However, Netflow data does not suit this case so well for the following reasons:
* Netflow data is very narrow, not wide (i.e fewer columns but more rows)
* The vast majority of load is write, not read
* Most queries will require almost all of the columns 
* ALL queries will require a timestamp related index
* It is very hard to do bulk adds as exported fields can change at any time and change per-exporter, but we generally only run one backend thread per exporter (this can be overridden if required of course).

Because of the above, I don't think it's a good fit so I won't add it without a real-world use case to motivate it - if you have such a thing, pop it in a comment or email and I will review and most likely add this as a feature request.

Thanks!
